### ISSUE TITLE
Todo list before release.

### ISSUE THREAD

**Issue by vudsen** [nextjs-particlex-theme/particlex#1]
- [x] SEO optimization
- [x] Archives page
- [x] Tags page
- [x] Categories page
- [x] Mobile adaptation
- [x] [Giscus](https://[giscus](https://giscus.app/zh-CN).app/zh-CN) support
- [x] Documentation
- [x] Final beautification
- [x] Image preview (2024/08/18)

**Comment by vudsen** [comment]
SEO: https://nextjs-particlex-theme.github.io/blog-config#seo

**Comment by vudsen** [comment]
Archives page: https://nextjs-particlex-theme.github.io/archives

**Comment by vudsen** [comment]
Documentation: https://nextjs-particlex-theme.github.io/archives

**Comment by IceOfSummer** [comment]
Final task: 
- [ ] Image preview

**Comment by vudsen** [comment]
Released: https://github.com/nextjs-particlex-theme/particlex/tree/v1-stabled
